language: node_js
node_js:
  - "12"
dist: trusty
branches:
  only:
  - master
git:
  depth: 3
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod --base-href https://reffcp.github.io/typescript-con-angular/


deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/typescript-con-angular
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: master