language: node_js
cache: 
  directories:
    - ~/.npm
node_js:
  - "12"
dist: trusty
branches:
  only:
  - master
git:
  depth: 3
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod


deploy:
  provider: pages
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

