language: node_js
cache: 
  directories:
    - ~/.npm
node_js:
  - "12"
dist: trusty
branches:
  only:
  - master
git:
  depth: 3
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod


deploy:
  provider: pages
  edge: true
  cleanup: false
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/typescript-con-angular
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: master

